### ISSUE TITLE
Add bootloader STM32_G071_BOOTLOADER_PA6_V8.hex

### ISSUE THREAD

**Issue by bhuism** [am32-firmware/AM32-unlocker#3]
Hi @tridge would you be able to add the bootloader for the PA6 signal line for the G071 'N'  mcu?

I want to flash the bootloader for an iflight blitz E55 (n version), some details here: https://github.com/am32-firmware/AM32/issues/52#issuecomment-2305835648

I flashed https://am32.ca/api/file/Ym9vdGxvYWRlcjpTVE0zMl9HMDcxX0JPT1RMT0FERVJfUEE2X1Y4LmhleA== ( STM32_G071_BOOTLOADER_PA6_V8.hex ) earlier using Stm32Cube32Programmer with needles on the pads, but I like your unlocker better :)

**Comment by tridge** [comment]
done
